version: '3.8'

services:
  app:
    build:
      context: .
    container_name: node-app
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DB_HOST=mysql
      - DB_USER=your-db-username
      - DB_PASSWORD=Nipun123@#
      - DB_NAME=your-database-name
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Nipun123@#
      MYSQL_DATABASE: your-database-name
      MYSQL_USER: your-db-username
      MYSQL_PASSWORD: Nipun123@#
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
